export const DummyAdmin = {
  fullName: "System Admin",
  email: "admin@foodapp.com",
  mobileNumber: "9000000000",
  password: "Admin@123",
  role: "admin",
  dob: "1990-01-01",
  gender: "others",
  address: "Head Office",
  city: "Delhi",
  pin: "110001",
  photo: {
    url: "",
    publicID: "",
  },
  geoLocation: {
    lat: "28.6139",
    lon: "77.2090",
  },
  paymentDetails: {
    upi: "admin@upi",
    account_number: "999999999999",
    ifs_Code: "ICIC0000001",
  },
  restaurantName: "N/A",
  cuisine: "N/A",
  documents: {
    gst: "N/A",
    fssai: "N/A",
    rc: "N/A",
    dl: "N/A",
    uidai: "999999999999",
    pan: "ADMIN1234Z",
  },
  isActive: "active",
};

export const DummyManagers = [
  {
    fullName: "Rakhi Yadav",
    email: "rakhiraj1686@gmail.com",
    mobileNumber: "9801436173",
    password: "Manager@123",
    role: "manager",
    dob: "2006-10-06",
    gender: "male",
    address: "Bhopal",
    pin: "462022",
    photo: {
      url: "https://res.cloudinary.com/ddavel3yu/image/upload/v1770986058/Cravings/User/xmnncti8cz4gxzkyiehl",
      publicID: "Cravings/User/xmnncti8cz4gxzkyiehl",
    },
    geolocation: {
      latitude: 23.2599,
      longitude: 77.4126,
    },
    paymentDetails: {
      accountHolderName: "Rakhi Yadav",
      accountNumber: "1234567890",
      ifscCode: "SBIN0001234",
      bankName: "State Bank of India",
    },
    restaurantName: "RICR Canteen",
    cuisine: "Indian",
    document: {
      gst: "29ABCDE1234F1Z5",
      fssai: "11223344556677",
      rc: "N/A",
      dl: "N/A",
      uidai: "123456789012",
      pan: "ABCDE1234F",
    },
    isActive: "active",
  },
  {
    fullName: "Amit Sharma",
    email: "amit.sharma@gmail.com",
    mobileNumber: "9876543210",
    password: "Manager@123",
    role: "manager",
    dob: "1998-04-12",
    gender: "male",
    address: "Indore",
    pin: "452001",
    photo: {
      url: "https://res.cloudinary.com/demo/image/upload/user2",
      publicID: "Cravings/User/user2",
    },
    geolocation: {
      latitude: 22.7196,
      longitude: 75.8577,
    },
    paymentDetails: {
      accountHolderName: "Amit Sharma",
      accountNumber: "9876543210",
      ifscCode: "HDFC0005678",
      bankName: "HDFC Bank",
    },
    restaurantName: "Spice Junction",
    cuisine: "North Indian",
    document: {
      gst: "27KLMNO9012P1Z3",
      fssai: "33445566778899",
      rc: "N/A",
      dl: "N/A",
      uidai: "345678901234",
      pan: "KLMNO9012P",
    },
    isActive: "active",
  },
  {
    fullName: "Neha Verma",
    email: "neha.verma@gmail.com",
    mobileNumber: "9123456780",
    password: "Manager@123",
    role: "manager",
    dob: "1995-08-21",
    gender: "female",
    address: "Delhi",
    pin: "110001",
    photo: {
      url: "https://res.cloudinary.com/demo/image/upload/user3",
      publicID: "Cravings/User/user3",
    },
    geolocation: {
      latitude: 28.6139,
      longitude: 77.209,
    },
    paymentDetails: {
      accountHolderName: "Neha Verma",
      accountNumber: "4567891230",
      ifscCode: "ICIC0001234",
      bankName: "ICICI Bank",
    },
    restaurantName: "Tandoori Treat",
    cuisine: "Mughlai",
    document: {
      gst: "27KLMNO9012P1Z3",
      fssai: "33445566778899",
      rc: "N/A",
      dl: "N/A",
      uidai: "345678901234",
      pan: "KLMNO9012P",
    },
    isActive: "inactive",
  },
  {
    fullName: "Rahul Singh",
    email: "rahul.singh@gmail.com",
    mobileNumber: "9012345678",
    password: "Manager@123",
    role: "manager",
    dob: "1992-12-15",
    gender: "male",
    address: "Mumbai",
    pin: "400001",
    photo: {
      url: "https://res.cloudinary.com/demo/image/upload/user4",
      publicID: "Cravings/User/user4",
    },
    geolocation: {
      latitude: 19.076,
      longitude: 72.8777,
    },
    paymentDetails: {
      accountHolderName: "Rahul Singh",
      accountNumber: "6543217890",
      ifscCode: "AXIS0007890",
      bankName: "Axis Bank",
    },
    restaurantName: "Bombay Bites",
    cuisine: "Street Food",
    document: {
      gst: "19FGHIJ5678K1Z2",
      fssai: "22334455667788",
      rc: "N/A",
      dl: "N/A",
      uidai: "234567890123",
      pan: "FGHIJ5678K",
    },
    isActive: "blocked",
  },
];

export const DummyPartners = [
  {
    fullName: "Aman Verma",
    email: "aman.partner1@gmail.com",
    mobileNumber: "9000000001",
    password: "Partner@123",
    role: "partner",
    dob: "1991-06-10",
    gender: "male",
    address: "Sector 21",
    city: "Noida",
    pin: "201301",
    photo: { url: "https://ui-avatars.com/api/?name=Aman+Verma", publicID: "" },
    geoLocation: { lat: "28.5355", lon: "77.3910" },
    paymentDetails: {
      upi: "aman@upi",
      account_number: "456789012345",
      ifs_Code: "SBIN0001234",
    },
    restaurantName: "Taste Junction",
    cuisine: "Fast Food",
    documents: {
      gst: "09ABCDE1234F1Z1",
      fssai: "55667788990011",
      rc: "N/A",
      dl: "N/A",
      uidai: "567856785678",
      pan: "ABCDE5678L",
    },
    isActive: "active",
  },
  {
    fullName: "Karan Malhotra",
    email: "karan.partner@gmail.com",
    mobileNumber: "9000000002",
    password: "Partner@123",
    role: "partner",
    dob: "1989-02-18",
    gender: "male",
    address: "Andheri West",
    city: "Mumbai",
    pin: "400058",
    photo: {
      url: "https://ui-avatars.com/api/?name=Karan+Malhotra",
      publicID: "",
    },
    geoLocation: { lat: "19.0760", lon: "72.8777" },
    paymentDetails: {
      upi: "karan@upi",
      account_number: "456789012346",
      ifs_Code: "HDFC0005678",
    },
    restaurantName: "Bombay Biryani House",
    cuisine: "Mughlai",
    documents: {
      gst: "27ABCDE2345F1Z2",
      fssai: "66778899001122",
      rc: "N/A",
      dl: "N/A",
      uidai: "678967896789",
      pan: "ABCDE6789M",
    },
    isActive: "inactive",
  },
  {
    fullName: "Ritika Sinha",
    email: "ritika.partner@gmail.com",
    mobileNumber: "9000000003",
    password: "Partner@123",
    role: "partner",
    dob: "1993-08-12",
    gender: "female",
    address: "Salt Lake",
    city: "Kolkata",
    pin: "700091",
    photo: {
      url: "https://ui-avatars.com/api/?name=Ritika+Sinha",
      publicID: "",
    },
    geoLocation: { lat: "22.5726", lon: "88.3639" },
    paymentDetails: {
      upi: "ritika@upi",
      account_number: "456789012347",
      ifs_Code: "ICIC0003344",
    },
    restaurantName: "Calcutta Flavours",
    cuisine: "Bengali",
    documents: {
      gst: "19ABCDE3456F1Z3",
      fssai: "77889900112233",
      rc: "N/A",
      dl: "N/A",
      uidai: "789078907890",
      pan: "ABCDE7890N",
    },
    isActive: "active",
  },
  {
    fullName: "Deepak Rao",
    email: "deepak.partner@gmail.com",
    mobileNumber: "9000000004",
    password: "Partner@123",
    role: "partner",
    dob: "1987-12-01",
    gender: "male",
    address: "Indiranagar",
    city: "Bangalore",
    pin: "560038",
    photo: { url: "https://ui-avatars.com/api/?name=Deepak+Rao", publicID: "" },
    geoLocation: { lat: "12.9716", lon: "77.5946" },
    paymentDetails: {
      upi: "deepak@upi",
      account_number: "456789012348",
      ifs_Code: "AXIS0001122",
    },
    restaurantName: "South Spice Hub",
    cuisine: "South Indian",
    documents: {
      gst: "29ABCDE4567F1Z4",
      fssai: "88990011223344",
      rc: "N/A",
      dl: "N/A",
      uidai: "890189018901",
      pan: "ABCDE8901P",
    },
    isActive: "blocked",
  },
];

export const DummyUsers = [
  {
    fullName: "Rohit Singh",
    email: "rohit.customer1@gmail.com",
    mobileNumber: "9654321870",
    password: "Customer@123",
    role: "customer",
    dob: "1995-11-03",
    gender: "male",
    address: "Ashok Nagar",
    city: "Lucknow",
    pin: "226001",
    photo: {
      url: "https://ui-avatars.com/api/?name=Rohit+Singh",
      publicID: "",
    },
    geoLocation: { lat: "26.8467", lon: "80.9462" },
    paymentDetails: {
      upi: "rohit@upi",
      account_number: "N/A",
      ifs_Code: "N/A",
    },
    restaurantName: "N/A",
    cuisine: "N/A",
    documents: {
      gst: "N/A",
      fssai: "N/A",
      rc: "N/A",
      dl: "N/A",
      uidai: "345634563456",
      pan: "ROHIT9012M",
    },
    isActive: "active",
  },
  {
    fullName: "Priya Nair",
    email: "priya.customer@gmail.com",
    mobileNumber: "9654321871",
    password: "Customer@123",
    role: "customer",
    dob: "2000-02-25",
    gender: "female",
    address: "MG Road",
    city: "Kochi",
    pin: "682016",
    photo: { url: "https://ui-avatars.com/api/?name=Priya+Nair", publicID: "" },
    geoLocation: { lat: "9.9312", lon: "76.2673" },
    paymentDetails: {
      upi: "priya@upi",
      account_number: "N/A",
      ifs_Code: "N/A",
    },
    restaurantName: "N/A",
    cuisine: "N/A",
    documents: {
      gst: "N/A",
      fssai: "N/A",
      rc: "N/A",
      dl: "N/A",
      uidai: "234523452345",
      pan: "PRIYA5678L",
    },
    isActive: "inactive",
  },
  {
    fullName: "Sneha Patel",
    email: "sneha.customer@gmail.com",
    mobileNumber: "9654321872",
    password: "Customer@123",
    role: "customer",
    dob: "1997-08-19",
    gender: "female",
    address: "SG Highway",
    city: "Ahmedabad",
    pin: "380015",
    photo: {
      url: "https://ui-avatars.com/api/?name=Sneha+Patel",
      publicID: "",
    },
    geoLocation: { lat: "23.0225", lon: "72.5714" },
    paymentDetails: {
      upi: "sneha@upi",
      account_number: "N/A",
      ifs_Code: "N/A",
    },
    restaurantName: "N/A",
    cuisine: "N/A",
    documents: {
      gst: "N/A",
      fssai: "N/A",
      rc: "N/A",
      dl: "N/A",
      uidai: "456745674567",
      pan: "SNEHA3456N",
    },
    isActive: "active",
  },
  {
    fullName: "Amit Verma",
    email: "amit.customer@gmail.com",
    mobileNumber: "9654321873",
    password: "Customer@123",
    role: "customer",
    dob: "1998-06-12",
    gender: "male",
    address: "Sector 14",
    city: "Gurgaon",
    pin: "122001",
    photo: { url: "https://ui-avatars.com/api/?name=Amit+Verma", publicID: "" },
    geoLocation: { lat: "28.4595", lon: "77.0266" },
    paymentDetails: { upi: "amit@upi", account_number: "N/A", ifs_Code: "N/A" },
    restaurantName: "N/A",
    cuisine: "N/A",
    documents: {
      gst: "N/A",
      fssai: "N/A",
      rc: "N/A",
      dl: "N/A",
      uidai: "123412341234",
      pan: "AMITV1234K",
    },
    isActive: "blocked",
  },
];

export const DummyMenus = [
  // 🍛 North Indian
  {
    restaurantID,
    itemName: "Paneer Butter Masala",
    cuisine: "North Indian",
    servingSize: "Full",
    preparationTime: "25 mins",
    type: "veg",
    description: "Creamy tomato gravy with paneer cubes.",
    price: "249",
    availability: "available",
    Image: [{ url: "https://dummyimage.com/paneer.jpg", publicID: "paneer1" }],
  },
  {
    restaurantID,
    itemName: "Dal Makhani",
    cuisine: "North Indian",
    servingSize: "Full",
    preparationTime: "30 mins",
    type: "veg",
    description: "Slow-cooked black lentils in buttery gravy.",
    price: "199",
    availability: "available",
    Image: [{ url: "https://dummyimage.com/dal.jpg", publicID: "dal1" }],
  },
  {
    restaurantID,
    itemName: "Butter Chicken",
    cuisine: "North Indian",
    servingSize: "Half",
    preparationTime: "35 mins",
    type: "non-veg",
    description: "Tender chicken in creamy tomato sauce.",
    price: "299",
    availability: "available",
    Image: [
      { url: "https://dummyimage.com/butterchicken.jpg", publicID: "bc1" },
    ],
  },
  {
    restaurantID,
    itemName: "Chicken Tikka",
    cuisine: "North Indian",
    servingSize: "8 Pieces",
    preparationTime: "20 mins",
    type: "non-veg",
    description: "Grilled spicy chicken tikka.",
    price: "279",
    availability: "available",
    Image: [{ url: "https://dummyimage.com/tikka.jpg", publicID: "tikka1" }],
  },
  {
    restaurantID,
    itemName: "Shahi Paneer",
    cuisine: "North Indian",
    servingSize: "Full",
    preparationTime: "25 mins",
    type: "veg",
    description: "Royal creamy paneer curry.",
    price: "239",
    availability: "available",
    Image: [{ url: "https://dummyimage.com/shahi.jpg", publicID: "shahi1" }],
  },

  // 🍕 Fast Food
  {
    restaurantID,
    itemName: "Margherita Pizza",
    cuisine: "Italian",
    servingSize: "Medium",
    preparationTime: "20 mins",
    type: "veg",
    description: "Classic cheese and tomato pizza.",
    price: "349",
    availability: "available",
    Image: [{ url: "https://dummyimage.com/pizza1.jpg", publicID: "pizza1" }],
  },
  {
    restaurantID,
    itemName: "Farmhouse Pizza",
    cuisine: "Italian",
    servingSize: "Medium",
    preparationTime: "25 mins",
    type: "veg",
    description: "Loaded with fresh vegetables.",
    price: "399",
    availability: "available",
    Image: [{ url: "https://dummyimage.com/pizza2.jpg", publicID: "pizza2" }],
  },
  {
    restaurantID,
    itemName: "Chicken Supreme Pizza",
    cuisine: "Italian",
    servingSize: "Medium",
    preparationTime: "25 mins",
    type: "non-veg",
    description: "Loaded with chicken and cheese.",
    price: "449",
    availability: "available",
    Image: [{ url: "https://dummyimage.com/pizza3.jpg", publicID: "pizza3" }],
  },
  {
    restaurantID,
    itemName: "Veg Burger",
    cuisine: "Fast Food",
    servingSize: "1 Piece",
    preparationTime: "10 mins",
    type: "veg",
    description: "Crispy veg patty burger.",
    price: "129",
    availability: "available",
    Image: [{ url: "https://dummyimage.com/burger1.jpg", publicID: "burger1" }],
  },
  {
    restaurantID,
    itemName: "Chicken Burger",
    cuisine: "Fast Food",
    servingSize: "1 Piece",
    preparationTime: "12 mins",
    type: "non-veg",
    description: "Juicy chicken patty burger.",
    price: "159",
    availability: "available",
    Image: [{ url: "https://dummyimage.com/burger2.jpg", publicID: "burger2" }],
  },

  // 🍜 Chinese
  {
    restaurantID,
    itemName: "Veg Hakka Noodles",
    cuisine: "Chinese",
    servingSize: "Full",
    preparationTime: "15 mins",
    type: "veg",
    description: "Stir-fried noodles with veggies.",
    price: "179",
    availability: "available",
    Image: [
      { url: "https://dummyimage.com/noodles1.jpg", publicID: "noodles1" },
    ],
  },
  {
    restaurantID,
    itemName: "Chicken Hakka Noodles",
    cuisine: "Chinese",
    servingSize: "Full",
    preparationTime: "18 mins",
    type: "non-veg",
    description: "Noodles with chicken and sauces.",
    price: "199",
    availability: "available",
    Image: [
      { url: "https://dummyimage.com/noodles2.jpg", publicID: "noodles2" },
    ],
  },
  {
    restaurantID,
    itemName: "Veg Fried Rice",
    cuisine: "Chinese",
    servingSize: "Full",
    preparationTime: "15 mins",
    type: "veg",
    description: "Fried rice with mixed vegetables.",
    price: "169",
    availability: "available",
    Image: [{ url: "https://dummyimage.com/rice1.jpg", publicID: "rice1" }],
  },
  {
    restaurantID,
    itemName: "Chicken Fried Rice",
    cuisine: "Chinese",
    servingSize: "Full",
    preparationTime: "18 mins",
    type: "non-veg",
    description: "Fried rice tossed with chicken.",
    price: "199",
    availability: "available",
    Image: [{ url: "https://dummyimage.com/rice2.jpg", publicID: "rice2" }],
  },
  {
    restaurantID,
    itemName: "Chilli Paneer",
    cuisine: "Chinese",
    servingSize: "Full",
    preparationTime: "20 mins",
    type: "veg",
    description: "Spicy paneer in Chinese sauce.",
    price: "219",
    availability: "available",
    Image: [{ url: "https://dummyimage.com/chilli1.jpg", publicID: "chilli1" }],
  },

  // 🍰 Desserts & Others (20 more simple variations)
  ...Array.from({ length: 20 }, (_, i) => ({
    restaurantID,
    itemName: `Special Dish ${i + 1}`,
    cuisine: "Multi Cuisine",
    servingSize: "Standard",
    preparationTime: `${15 + i} mins`,
    type: i % 2 === 0 ? "veg" : "non-veg",
    description: "Chef's special delicious dish.",
    price: `${199 + i * 10}`,
    availability: "available",
    Image: [
      {
        url: "https://dummyimage.com/special.jpg",
        publicID: `special${i + 1}`,
      },
    ],
  })),
];
